riot-login:
    persist:
        region: "EUW"
        scopes:
        - "openid"
        - "link"
        - "ban"
        - "lol_region"
        - "lol"
        - "summoner"
        - "offline_access"
        session:
            cookies:
            -   domain: "auth.riotgames.com"
                hostOnly: true
                httpOnly: true
                name: "asid"
                path: "/"
                persistent: false
                secureOnly: true
                value: "ZN8Qyo9_r_0DxEAu_dn8VOwVP8GLz23BoG5V7_b9xaA"
            -   domain: "auth.riotgames.com"
                hostOnly: true
                httpOnly: true
                name: "ccid"
                path: "/"
                persistent: true
                secureOnly: true
                value: "riot-client"
            -   domain: "auth.riotgames.com"
                hostOnly: true
                httpOnly: true
                name: "clid"
                path: "/"
                persistent: true
                secureOnly: true
                value: "ec1"
            -   domain: "auth.riotgames.com"
                hostOnly: true
                httpOnly: true
                name: "sub"
                path: "/"
                persistent: true
                secureOnly: true
                value: "39f47fce-9e57-5fff-ab47-99c523b52843"
            -   domain: "auth.riotgames.com"
                hostOnly: true
                httpOnly: true
                name: "csid"
                path: "/"
                persistent: true
                secureOnly: true
                value: "eGNlIDRJJH845NE8dAhDqw.Ah1ut83q1KtgLCU_pzImcg"
            -   domain: "auth.riotgames.com"
                hostOnly: true
                httpOnly: true
                name: "ssid"
                path: "/"
                persistent: true
                secureOnly: true
                value: "eyJhbGciOiJIUzI1NiJ9.eyJsb2dpblRva2VuIjoiZTNjZDJhMTUtYmM5Yi00ZmJmLWIyOGItYWQ1ZDkzYTY1MmIzIiwic3ViIjoiMzlmNDdmY2UtOWU1Ny01ZmZmLWFiNDctOTljNTIzYjUyODQzIiwic2VyaWVzVG9rZW4iOiI2MTFlNDRiMS1lZmNlLTQ3OTgtOTU3Yi0yMmU2YTZhNjUwMDUiLCJzc2lkIjoiZUdObElEUkpKSDg0NU5FOGRBaERxdy5BaDF1dDgzcTFLdGdMQ1VfcHpJbWNnIiwiaWF0IjoxNzYzNjM0NjQ4fQ.sCo3lapZbd8H_3YmPhzi228Naz_jghcEbLsV43e1K9w"
rso-authenticator:
    tdid:
        domain: "riotgames.com"
        expiryTime: 1795170646
        hostOnly: false
        httpOnly: true
        name: "tdid"
        path: "/"
        persistent: true
        secureOnly: true
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwZTIxZTFhLTM4NGItNGI3Yy05YjRlLWZjZDY0ZDY1OTE1ZiIsIm5vbmNlIjoiWFVkbnRudWs1K1k9IiwiaWF0IjoxNzYzNjM0NjQ3fQ.WDZxVcSiOz3BkMQ_keQ9w0iIaMWmam7zDFujCtvEL74"
